name: CI - FAST Testing

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test-playwright:
    name: ${{ matrix.os }} Playwright@${{ matrix.playwright}} headless=${{ matrix.headless }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        playwright: [latest]
        headless: [true, false]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: ./
    - name: Install dependencies
      run: cd fast/build/testing && npm install playwright@${{ matrix.playwright }}

    - name: Run Playwright (headless)
      if: ${{ matrix.headless == true }}
      run: cd fast/build/testing && node playwright-automation.js

    - name: Run Playwright (headful linux)
      if: ${{ matrix.headless == false && startsWith(matrix.os, 'ubuntu') }}
      run: cd fast/build/testing && HEADFUL=true xvfb-run --auto-servernum -- node playwright-automation.js
    - name: Run Playwright (headful windows)
      if: ${{ matrix.headless == false && startsWith(matrix.os, 'windows') }}
      run: cd fast/build/testing && HEADFUL=true node playwright-automation.js
      shell: bash
    - name: Run Playwright (headful mac)
      if: ${{ matrix.headless == false && startsWith(matrix.os, 'mac') }}
      run: cd fast/build/testing && HEADFUL=true node playwright-automation.js
